### ISSUE TITLE
Login with Bearer Token not working

### ISSUE THREAD

**Issue by ahus1** [dukecon/dukecon_feedback#6]
I've tested the new keycloak setup and it seems to work with the browser and redirects, but not with the Bearer Tokens we need for our Single Page App.

I suggest to integrate the standard Keycloak adapter in the feedback application. 

Please comment if this is how to proceed / cc: @ascheman

**Comment by ascheman** [comment]
Thanks, sounds good to me!
But there is also an ongoing discussion on the German JVM-Slack with @thomasdarimont and others, cf. https://jvm-german.slack.com/archives/C4HN8JNT1/p1523971846000755

**Comment by ahus1** [comment]
Changes are now in a separate branch. Reading the "but" in your email - should I wait?

**Comment by ahus1** [comment]
It's now in the develop Branch and deployed on latest.
